#!/usr/bin/env bash
#
# Regenerate per-unit requirements files from pyproject.toml.
#
# Run after editing dependencies in pyproject.toml. The resulting
# `requirements/unit-N.txt` files are what `setup_colab.py` fetches at
# notebook runtime on Colab. They are committed to the repo.
#
# Usage:
#     bash scripts/export-requirements.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."

mkdir -p requirements

for UNIT in unit-1 unit-2 unit-3 unit-4 unit-5; do
    OUT="requirements/${UNIT}.txt"
    echo "=> exporting ${UNIT} -> ${OUT}"
    if uv export --extra "${UNIT}" --no-hashes --no-emit-project --output-file "${OUT}" 2>/dev/null; then
        :
    else
        # Empty extra — write a stub so setup_colab.py's fetch doesn't 404.
        cat > "${OUT}" <<EOF
# Auto-generated by scripts/export-requirements.sh
# ${UNIT} has no dependencies yet — populated when unit is built.
EOF
    fi
done

echo
echo "done. review and commit the regenerated requirements/ files:"
echo "  git add requirements/ && git commit -m 'requirements: regenerate from pyproject.toml'"
